const daySinceFirstCode = new Date('01/22/2019');
const todayDate = new Date();
const time = todayDate.getTime() - daySinceFirstCode.getTime();
const days = Math.floor(time / (1000 * 3600 * 24));
const codedDaysString = 'Coded For ' + days + ' Days Straight';

/* eslint-disable max-len */

const thoughts = [
    codedDaysString,
    'Let’s Make the World Better with Software',
    'Student',
    'Go Bears!',
    'UC Berkeley',
    'Not Your Average Techie',
    'Artificial Intelligence',
    'Machine Learning',
    'Kaggler',
    'Computer Science',
    '안녕!',
    '你好!',
    'Software Engineer',
    'Software Developer',
    '❤️ open source',
    'I ❤️ GitHub',
    'PICTure Research Group',
    'Coffee. Code. Sleep. Repeat.',
    '#DarkModeEverything',
    'Computer Architecture',
    '#ComputerArchitecture',
    'RISC-V',
    '#parallelism',
    'Linux Enthusiast',
    'macOS',
    'Educator',
    'NumS',
    'RISELab',
    'Sky Computing',
    'UC Berkeley RISELab',
    'UC Berkeley Sky Computing',
    'NCSU Systems Lab',
    'Charlotte, NC',
    'San Francisco, CA',
    'San Francisco Bay Area',
    'Bay Area',
    'Some people worry that artificial intelligence will make us feel inferior, but then, anybody in his right mind should have an inferiority complex every time he looks at a flower',
    'People who are really serious about software should make their own hardware',
    'The best way to predict the future is to invent it',
    'The only way to do great work is to love what you do',
    'Simple things should be simple, complex things should be possible',
    'The most important applications of computers has been designing better computers',
    'You can’t connect the dots looking forward; you can only connect them looking backwards',
    'Your time is limited, so don’t waste it living someone else’s life',
    'Don’t let the noise of others’ opinions drown out your own inner voice',
    'Have the courage to follow your heart and intuition; they somehow already know what you truly want to become',
    'He who says he can and he who says he can’t are both usually right',
    'It ain\'t about how hard you can hit; it’s about how hard you can get hit and keep moving forward',
    'California',
    'North Carolina',
    '<span class=\'apple-logo\'></span>',
    'SWE Intern @ <span class=\'apple-logo\'></span>',
    'SWE @ <span class=\'apple-logo\'></span>',
    'ML Compiler Engineer @ <span class=\'apple-logo\'></span>',
    'ML Compiler Engineer',
    'Autograd',
    'Addicted to making code go fast 🏎️💨',
    'Addicted to making code go brrr',
    'Addicted to making code go zoom zoom',
    'Addicted to making code go vroom vroom',
    'Accelerate',
    'Basic Neural Network Subroutines',
    'BNNS',
    'Siri',
    'CNN',
    'LLM',
    'LLVM',
    'RNN',
    'Python',
    'C',
    'C++',
    'BLAS',
    'LAPACK',
    'MKL',
    'Intel MKL',
    'Intel Math Kernel Library',
    'NumPy',
    'Transformers',
    'PyTorch',
    'TensorFlow',
    'processing',
    'p5',
    'This is Perlin Noise',
    'Perlin Noise',
    'Perlin Noise is Cool',
    'Class of 2022',
    'UC Berkeley 2022',
    'ARM',
    'Apple Intern',
    'Compilers',
    '<span class=\'apple-logo\'></span><span class=\'apple-logo\'></span><span class=\'apple-logo\'></span>',
    'hello world.',
    'Hello World!',
    'he/him/his',
    'North Carolina State University',
    'NCSU',
    'NCSU 2024',
    'print("Hello World!")',
    'Peak Performance',
    'Performance Addict',
    'Speed',
    'High Performance Computing',
    'High Performance',
    'The Name of the Game is Speed',
    'AVX-512',
    'AVX2',
    'SVE',
    'SME',
    '<tt>ZMM0</tt>',
    '<tt>XMM0</tt>',
    '<tt>YMM0</tt>',
    '<tt>vector</tt>',
    '<tt>malloc</tt>',
    '<tt>mkl_malloc</tt>',
    '<tt>#pragma omp for</tt>',
    '<tt>_mm512_fmadd_pd</tt>',
    '<tt>MPI_Send</tt>',
    '<tt>MPI_Recv</tt>',
    '<tt>MPI_Recv</tt>',
    '<tt>cudaMalloc</tt>',
    'GEMM',
    'NCCL',
    'MPI',
    'OpenMP',
    'SIMD',
    'GPU',
    'CUDA',
    'ASM',
    'Slurm',
    'HPC',
    'NEON',
];

// Shuffle the thoughts
thoughts.sort(function() {
    return 0.5 - Math.random();
});

const options = {
    strings: thoughts,
    typeSpeed: 25,
    backSpeed: 5,
    backDelay: 2000,
    loop: true,
    showCursor: false,
};

// eslint-disable-next-line no-unused-vars
const typed = new Typed('#quote', options);
